export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const GET_USER = "GET_USER";
export const GET_USER_FAIL= "GET_USER_FAIL";

export const ALL_USERS = "ALL_USERS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ADMIN_SUCCESS = "LOGIN_ADMIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const GET_NEWS = "GET_NEWS";

export const GET_DETAIL_NEWS = "GET_DETAIL_NEWS";

export const GET_DETAIL_USER = "GET_DETAIL_USER";

export const UPLOAD_NEWS_SUCCESS = "UPLOAD_NEWS_SUCCESS";
export const UPLOAD_NEWS_FAIL = "UPLOAD_NEWS_FAIL";

export const GET_DATA_CATEGORY = "GET_DATA_CATEGORY";

export const GET_CATEGORIES_PAGINATION = "GET_CATEGORIES_PAGINATION";

export const GET_VIDEO = "GET_VIDEO";

export const GET_SINGLE_USER = "GET_SINGLE_USER";

export const GET_STATUS_NEWS_USER = "GET_STATUS_NEWS_USER";

export const GET_NEWS_SEARCH = "GET_NEWS_SEARCH";


